import { chromium } from "@playwright/test";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
await p.goto("http://localhost:5173/", { waitUntil: "networkidle" });
await p.locator('[data-testid="preloader"]').waitFor({ state: "detached" }).catch(()=>{});
await sleep(800);
await p.addScriptTag({ url: "https://cdnjs.cloudflare.com/ajax/libs/axe-core/4.10.2/axe.min.js" });
const r = await p.evaluate(async () => (await window.axe.run(document, { runOnly: { type:"tag", values:["wcag2a","wcag2aa","wcag21a","wcag21aa"] }})).violations.map(v=>`[${v.impact}] ${v.id} (${v.nodes.length})`));
console.log("VIOLATIONS:", r.length, r.join(" | "));
await b.close();
