/**
 * Pulls the latin cuts of the three families out of Google Fonts and writes
 * them into public/fonts, plus the @font-face rules that point at them.
 *
 * Self-hosting is not a micro-optimisation here. With the fonts coming from
 * fonts.gstatic.com, what got rendered depended on whether that fetch had
 * landed yet, so CI screenshotted fallback metrics while this machine — which
 * happens to have Inter installed — never showed the problem. Same-origin
 * files render the same everywhere.
 *
 * Run with: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap";

// A browser UA, or Google serves the ttf fallback stylesheet instead of woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = join(process.cwd(), "public", "fonts");
const CSS_OUT = join(process.cwd(), "src", "styles", "fonts.css");

const css = await fetch(CSS_URL, { headers: { "User-Agent": UA } }).then((r) =>
  r.text(),
);

/** Each face in the response is preceded by a `/* subset *\/` comment. */
const blocks = [
  ...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*{[^}]+})/g),
];

/**
 * All three are variable fonts, so every requested weight of a family comes
 * back pointing at one file. Group by URL and emit a single face per family
 * carrying a weight range, rather than four identical copies of Inter.
 */
const faces = new Map();
for (const [, subset, block] of blocks) {
  // Latin alone. The site has no Cyrillic, Greek or Vietnamese copy, and
  // shipping those would multiply the payload for nothing.
  if (subset !== "latin") continue;

  const url = /url\(([^)]+)\)/.exec(block)[1];
  const face = faces.get(url) ?? {
    family: /font-family:\s*'([^']+)'/.exec(block)[1],
    range: /unicode-range:\s*([^;]+)/.exec(block)[1],
    weights: [],
  };
  face.weights.push(Number(/font-weight:\s*(\d+)/.exec(block)[1]));
  faces.set(url, face);
}

const rules = [];
await mkdir(OUT_DIR, { recursive: true });

for (const [url, face] of faces) {
  const slug = face.family.toLowerCase().replace(/\s+/g, "-");
  const file = `${slug}.woff2`;
  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  await writeFile(join(OUT_DIR, file), bytes);

  const low = Math.min(...face.weights);
  const high = Math.max(...face.weights);
  const weight = low === high ? `${low}` : `${low} ${high}`;
  console.log(
    `${file}  ${(bytes.length / 1024).toFixed(1)}kB  weights ${weight}`,
  );

  rules.push(
    [
      "@font-face {",
      `  font-family: '${face.family}';`,
      "  font-style: normal;",
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      // Plain woff2, even though these are variable. Chrome treats the older
      // 'woff2-variations' hint as an unsupported format, drops the face, and
      // quietly falls back — which looks fine on a machine that has the family
      // installed and wrong everywhere else.
      `  src: url('/fonts/${file}') format('woff2');`,
      `  unicode-range: ${face.range};`,
      "}",
    ].join("\n"),
  );
}

const header = `/**
 * Self-hosted so every environment renders the same glyphs. Generated by
 * scripts/fetch-fonts.mjs — edit that, not this.
 */

`;
await writeFile(CSS_OUT, header + rules.join("\n\n") + "\n");
console.log(`\n${rules.length} faces -> ${CSS_OUT}`);
