/**
 * Pulls the latin cuts of the three families out of Google Fonts into
 * public/fonts, plus the @font-face rules pointing at them. Self-hosted so
 * every environment renders the same glyphs rather than whatever arrives first.
 *
 * Run with: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap";

// A browser UA, or Google serves the ttf fallback stylesheet instead of woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = join(process.cwd(), "public", "fonts");
const CSS_OUT = join(process.cwd(), "src", "styles", "fonts.css");

const css = await fetch(CSS_URL, { headers: { "User-Agent": UA } }).then((r) =>
  r.text(),
);

/** Each face in the response is preceded by a `/* subset *\/` comment. */
const blocks = [
  ...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*{[^}]+})/g),
];

/**
 * All three are variable fonts, so every requested weight of a family points at
 * one file. Group by URL and emit a single face per family with a weight range.
 */
const faces = new Map();
for (const [, subset, block] of blocks) {
  // Latin alone; the site has no Cyrillic, Greek or Vietnamese copy.
  if (subset !== "latin") continue;

  const url = /url\(([^)]+)\)/.exec(block)[1];
  const face = faces.get(url) ?? {
    // Suffixed so an installed copy cannot shadow the face: Chrome will satisfy
    // `font-family: Inter` from the system and leave ours unloaded.
    family: `${/font-family:\s*'([^']+)'/.exec(block)[1]} Web`,
    slug: /font-family:\s*'([^']+)'/
      .exec(block)[1]
      .toLowerCase()
      .replace(/\s+/g, "-"),
    range: /unicode-range:\s*([^;]+)/.exec(block)[1],
    weights: [],
  };
  face.weights.push(Number(/font-weight:\s*(\d+)/.exec(block)[1]));
  faces.set(url, face);
}

const rules = [];
await mkdir(OUT_DIR, { recursive: true });

for (const [url, face] of faces) {
  const file = `${face.slug}.woff2`;
  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  await writeFile(join(OUT_DIR, file), bytes);

  const low = Math.min(...face.weights);
  const high = Math.max(...face.weights);
  const weight = low === high ? `${low}` : `${low} ${high}`;
  console.log(
    `${file}  ${(bytes.length / 1024).toFixed(1)}kB  weights ${weight}`,
  );

  rules.push(
    [
      "@font-face {",
      `  font-family: '${face.family}';`,
      "  font-style: normal;",
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      // Plain woff2 even though these are variable; Chrome drops the face if
      // told 'woff2-variations'.
      `  src: url('/fonts/${file}') format('woff2');`,
      `  unicode-range: ${face.range};`,
      "}",
    ].join("\n"),
  );
}

const header = `/**
 * Self-hosted so every environment renders the same glyphs. Generated by
 * scripts/fetch-fonts.mjs — edit that, not this.
 */

`;
await writeFile(CSS_OUT, header + rules.join("\n\n") + "\n");
console.log(`\n${rules.length} faces -> ${CSS_OUT}`);
